# to show what context and vars available 
#- name: Print GitHub context
#  run: echo '${{ toJson(github) }}'
# github.* secrets.* vars.* env


name: Post welcome comment
on:
  pull_request:
    types: [opened]
permissions:
  pull-requests: write
jobs:
  welcome:
    name: Post welcome comment
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub context
        run: echo '${{ toJson(github) }}'
        
      - name: Post Welcome Comment
        run: gh pr comment "$PR_URL" --body "Welcome to the repository, see above for context!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}

